{% set name = "pyemma_tutorials" %}
{% set version = "0.3" %}
{% set sha256 = "b08c41e21fcaf78c9ebfc89a68c1c552aef0add992981ba70b8f4fa42e34f968" %}

package:
  name: {{ name }} 
  version: {{ version }} 

source:
  url: https://github.com/markovmodel/{{name}}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  script: python -m pip install --no-deps --ignore-installed . -v
  number: 1
  entry_points:
    - pyemma_tutorials = pyemma_tutorials.cli:main

  osx_is_app: True
  noarch: python


requirements:
  build:
    - pip
  run:
    - pyemma >=2.5.4
    - mdshare
    - notebook
    - nglview >=1.1.3
    - jupyter_contrib_nbextensions
    - nbexamples

test:
  imports:
    - pyemma_tutorials
  commands:
    - which pyemma_tutorials  # [linux or osx]

about:
  home: https://github.com/markovmodel/pyemma_tutorials
  license: Creative Commons Attribution 4.0 
  license_family: CC 
  license_file: LICENSE
  summary: 'PyEMMA tutorial notebooks'
  description: |
    A collection of Jupyter notebooks, which introduce the usage of PyEMMA to build kinetic models
  doc_url: https://github.com/markovmodel/pyemma_tutorials
  dev_url: https://github.com/markovmodel/pyemma_tutorials

extra:
  recipe-maintainers:
    - marscher 
    - cwehmeyer
