{% set name = "pyemma_tutorials" %}
{% set version = "1.0" %}
{% set sha256 = "9ce0b5e16a8f732fbf295e691029068395cd401eebd8dead3e6615c3c1945b2d" %}

package:
  name: {{ name }} 
  version: {{ version }} 

source:
  url: https://github.com/markovmodel/{{name}}/archive/final-published-version-V1.tar.gz
  sha256: {{ sha256 }}

build:
  script: python -m pip install --no-deps --ignore-installed . -v
  number: 0
  entry_points:
    - pyemma_tutorials = pyemma_tutorials.cli:main

  osx_is_app: True
  noarch: python


requirements:
  build:
    - pip
  run:
    - pyemma >=2.5.5
    - mdshare >=0.4.0
    - notebook
    - nglview >=1.1.3
    - jupyter_contrib_nbextensions
    - nbexamples

test:
  imports:
    - pyemma_tutorials
  commands:
    - which pyemma_tutorials  # [linux or osx]

about:
  home: https://github.com/markovmodel/pyemma_tutorials
  license: Creative Commons Attribution 4.0 
  license_family: CC 
  license_file: LICENSE
  summary: 'PyEMMA tutorial notebooks'
  description: |
    A collection of Jupyter notebooks, which introduce the usage of PyEMMA to build kinetic models
  doc_url: https://github.com/markovmodel/pyemma_tutorials
  dev_url: https://github.com/markovmodel/pyemma_tutorials

extra:
  recipe-maintainers:
    - marscher 
    - cwehmeyer
