travis:
  secure:
    BINSTAR_TOKEN: jxgw59DxPuZamjbivOKw+JN3p1KWmaIP5RKRuxIE9BIw+n3alHoaJ8N19p2XSQ6jP8VseEvNB74MLbazvZuy7/xvyF9Ew8BAjzd79PLZ5cjNTE53eTNSNlH6r6PdwR0z+NGjIZbaxr+PQtFrNGVKuNzF7a9wIz9sBSh3/MDduEx7jbwWDdmqbiS6HS1mtXWtnDIJBlBf65PuN7fkq+MGrikpHJenZxKPhPfQezRCMu+zyPsD9bnPMcfqtiSMCTjZv48ZP0UVgk/Tt0ulOmM7mWbk18c3bXEokEfvvQmXviNBNi7Lp/4SzJxOt52W4Cv7lI6jiTlOIEXZaCjLdyHfdFRjqcKUSV677HCUJGdMRN7mR7wf9s4MrQ0lhKqInjIK646HSlf8rl7Zr7vC08wsdRVhgEWcycG5lqjwbw1yVsJokEexuTf/KPCcqMOZ4D4vCDhAD9zeg9Z2VfyTJqfRnDP0LWv0kNLqD2wnZpFECXFLf5NFaoX2QoXIL6Y2Na9tmLn4pghTkaRvrF5A8IhHHweGrq+wXmJp/egF7JgHDX1HtKyIIIACpEzjwAH02ohIPFhf/ZxDlLHABKGrgYvjUJX9lAD6OGMfpryy1B7Hb8utB5z+wH841npRk94uxCIMkVYjEgnye32Qp7UsYNJvHroex7DM+qj8vuMEUjmhj9U=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
