travis:
  secure:
    BINSTAR_TOKEN: SnV+yrKz94e5ULJczYWZtxXYmSk5yBqKdtyndCxowP6NiFLACIy6YNRtqhzbQMyL74j0TScoc+OmFUr3Agtl2jAsGuvhw/YFz88virViqt9QRGDyhSxziFI1Ll9w3tAq3HFfK6tq8R6e3hhUebUjG5usQevQ9M96xbz0SMASWalxhKOJHluUT9QU+WdX4miNruENTakRZr5DU3K1lAtZmtuP3dwB7G/DE3V4xx6sebNFzXz9uSLdR867uruiqw0J/nbRFh7yVEJQX5JVGkJ73M2xKCv9K8OtdAaI7dwPBlx3JXlutLz6M2VTRpPvzjYGMOKqTKpHnU6kt7PiQSiEfgVZdyS6AiPUsKqS7Hb24lc4SEjsxNQFr/uGckcDh54vZ1pWr96q09PFGaMVJug8HswIv8bQ5BdxwI9jrIFTMAC0e5H7Gb/Hp6L0cJNfcwkIHVncBNCEMFtR+30wR8QRIrpirTW3QNQcohSHFPXMF6HMEXKptj0M2DNAbCdk7PqflQ6/NDi8FyNWbPIuPQjYtPwSf2M0bmRshPwuJnW0z03dZQ3BVcwVmIaEP5lb+wYCoSM9Se08oROhii25CHf8GptaOo/vznELxIAF4VF8L60euze14GxAkMvngSc6/Q28AarWmX0MWtnPVE0rgyDvHG0aKi0Q2Vk/Vcm6wtVYJx8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
